"""Pydantic models for LLM-structured output."""
from __future__ import annotations

import ipaddress
import json
import re
from pathlib import Path
from typing import Literal
from pydantic import BaseModel, Field, field_validator

INTENTS = {
    "reconnaissance", "initial_access", "execution", "persistence",
    "privilege_escalation", "defense_evasion", "credential_access",
    "discovery", "lateral_movement", "collection", "command_and_control",
    "exfiltration", "impact", "cryptomining", "benign", "unknown",
}


# ---------------------------------------------------------------------------
# MITRE ATT&CK validation
# ---------------------------------------------------------------------------
# The slim ID list is vendored at `dshield_enrich/data/mitre_attack_ids.json`
# and regenerated by `scripts/vendor_mitre_attack.py`. Loaded once at import.
_MITRE_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "mitre_attack_ids.json"

try:
    _mitre_blob = json.loads(_MITRE_DATA_PATH.read_text())
    MITRE_TACTIC_IDS: frozenset[str] = frozenset(_mitre_blob.get("tactics") or ())
    MITRE_TECHNIQUE_IDS: frozenset[str] = frozenset(_mitre_blob.get("techniques") or ())
except (OSError, ValueError):
    # Fail-soft: if the vendored data is missing, drop all IDs rather than
    # silently letting hallucinated values through.
    MITRE_TACTIC_IDS = frozenset()
    MITRE_TECHNIQUE_IDS = frozenset()

# Observability: count IDs the LLM emitted that didn't match the vendored set.
# Read via `mitre_drop_counts()` from monitoring / healthcheck.
_mitre_drops: dict[str, int] = {"tactics": 0, "techniques": 0}


def mitre_drop_counts() -> dict[str, int]:
    """Return a snapshot of how many MITRE IDs have been dropped as invalid
    since process start. Tracks LLM hallucination rate cheaply."""
    return dict(_mitre_drops)


def reset_mitre_drop_counts() -> None:
    _mitre_drops["tactics"] = 0
    _mitre_drops["techniques"] = 0


def _validate_mitre_ids(
    raw: list[str], valid: frozenset[str], kind: str
) -> list[str]:
    """Normalise (uppercase, strip) the LLM's tactic/technique IDs and drop any
    that aren't in the vendored ATT&CK set. Increments the drop counter for
    each rejection so we can observe hallucination rate."""
    out: list[str] = []
    for s in raw or ():
        if not s or not isinstance(s, str):
            continue
        norm = s.strip().upper()
        if not norm:
            continue
        if norm in valid:
            out.append(norm)
        else:
            _mitre_drops[kind] += 1
    return out


# Anchored hex matchers for MD5 / SHA1 / SHA256 hash IOCs.
_HASH_RE   = re.compile(r"^[A-Fa-f0-9]+$")
_HASH_LENS = {32, 40, 64}
# Conservative domain matcher — labels of letters/digits/hyphens separated
# by dots, with a TLD of >= 2 letters. Rejects bare words like "PING".
_DOMAIN_RE = re.compile(
    r"^(?=.{1,253}$)"
    r"(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+"
    r"[A-Za-z]{2,}$"
)


def _looks_like_url(s: str) -> bool:
    s = s.lower()
    return s.startswith(("http://", "https://", "ftp://", "ftps://", "tftp://"))


class IOCs(BaseModel):
    """LLM-extracted indicators. Each field is filtered to drop entries that
    don't match the field's surface shape. Reason: the local model
    occasionally hallucinates non-IOC strings into these lists (e.g. command
    names like "PING" landing in `ips`). The downstream ES mapping enforces
    strict types on `threat.indicator.ip`, so a single bad string used to
    fail the whole bulk write for the doc. Filtering here is fail-soft —
    invalid entries are dropped rather than raising so the rest of the
    enrichment still lands."""
    urls: list[str] = Field(default_factory=list)
    ips: list[str] = Field(default_factory=list)
    domains: list[str] = Field(default_factory=list)
    files: list[str] = Field(default_factory=list)
    hashes: list[str] = Field(default_factory=list)

    @field_validator("ips", mode="before")
    @classmethod
    def _filter_ips(cls, v) -> list[str]:
        if not isinstance(v, list):
            return []
        out: list[str] = []
        for s in v:
            if not s or not isinstance(s, str):
                continue
            s = s.strip().rstrip(".").strip("[]")
            if not s:
                continue
            try:
                ipaddress.ip_address(s)
            except ValueError:
                continue
            out.append(s)
        return out

    @field_validator("hashes", mode="before")
    @classmethod
    def _filter_hashes(cls, v) -> list[str]:
        if not isinstance(v, list):
            return []
        out: list[str] = []
        for s in v:
            if not s or not isinstance(s, str):
                continue
            s = s.strip().lower()
            if len(s) in _HASH_LENS and _HASH_RE.match(s):
                out.append(s)
        return out

    @field_validator("domains", mode="before")
    @classmethod
    def _filter_domains(cls, v) -> list[str]:
        if not isinstance(v, list):
            return []
        out: list[str] = []
        for s in v:
            if not s or not isinstance(s, str):
                continue
            s = s.strip().rstrip(".").lower()
            if not s or "/" in s or " " in s:
                continue
            if _DOMAIN_RE.match(s):
                out.append(s)
        return out

    @field_validator("urls", mode="before")
    @classmethod
    def _filter_urls(cls, v) -> list[str]:
        if not isinstance(v, list):
            return []
        return [s.strip() for s in v if isinstance(s, str) and _looks_like_url(s.strip())]

    @field_validator("files", mode="before")
    @classmethod
    def _filter_files(cls, v) -> list[str]:
        if not isinstance(v, list):
            return []
        # File paths/names — loose check. Reject anything that's clearly not a
        # filesystem reference (no spaces, has at least one alpha/digit).
        out: list[str] = []
        for s in v:
            if not s or not isinstance(s, str):
                continue
            s = s.strip()
            if not s or " " in s:
                continue
            if any(ch.isalnum() for ch in s):
                out.append(s)
        return out


class CommandEnrichment(BaseModel):
    description: str
    intent: str
    tactics: list[str] = Field(default_factory=list)
    techniques: list[str] = Field(default_factory=list)
    iocs: IOCs = Field(default_factory=IOCs)
    confidence: int = 1  # 1-10 scale, see prompt for anchors

    @field_validator("intent")
    @classmethod
    def _intent_in_set(cls, v: str) -> str:
        v2 = v.strip().lower()
        return v2 if v2 in INTENTS else "unknown"

    @field_validator("confidence", mode="before")
    @classmethod
    def _coerce_confidence(cls, v) -> int:
        # Accept ints, floats, and stringified numbers. Clamp 1..10.
        try:
            n = float(v)
        except (TypeError, ValueError):
            return 1
        # If a model returns 0..1 (legacy float), rescale to 1..10
        if 0.0 <= n <= 1.0 and not isinstance(v, int):
            n = n * 10
        return max(1, min(10, int(round(n))))

    @field_validator("tactics")
    @classmethod
    def _validate_tactics(cls, v: list[str]) -> list[str]:
        return _validate_mitre_ids(v, MITRE_TACTIC_IDS, "tactics")

    @field_validator("techniques")
    @classmethod
    def _validate_techniques(cls, v: list[str]) -> list[str]:
        return _validate_mitre_ids(v, MITRE_TECHNIQUE_IDS, "techniques")


class CloudCommandEnrichment(CommandEnrichment):
    """Cloud (Claude) variant adds optional analyst notes (actor/campaign hypotheses)."""
    notes: str = ""


class PlaybookName(BaseModel):
    """LLM-named session cluster: short label plus a one-sentence rationale."""
    playbook_name: str
    rationale: str = ""

    @field_validator("playbook_name")
    @classmethod
    def _clean_name(cls, v: str) -> str:
        v = (v or "").strip().strip('"').strip("'").rstrip(".")
        words = v.split()
        if len(words) > 5:
            words = words[:5]
        return " ".join(words)


PLAYBOOK_NAME_JSON_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "playbook_name": {
            "type": "string",
            "description": "3-5 word playbook label, no surrounding quotes or trailing punctuation.",
            "minLength": 3,
            "maxLength": 80,
        },
        "rationale": {
            "type": "string",
            "description": "One short sentence (<=160 chars) on what evidence drove the name.",
            "maxLength": 200,
        },
    },
    "required": ["playbook_name"],
    "additionalProperties": False,
}


# ---------------------------------------------------------------------------
# Cluster-pair explanation (interactive: "why didn't these two playbooks merge?")
# ---------------------------------------------------------------------------

# Closed verdict set so the frontend can colour/icon the result deterministically.
CLUSTER_PAIR_VERDICTS = {
    "semantic_split",      # different commands; embedding gap is the cause
    "behavioural_split",   # similar commands; scalar block kept them apart
    "both",                # both semantic and behavioural diffs contribute
    "marginal_split",      # centroid sim is near threshold; many small things keep them apart
    "near_duplicate",      # sim ≥ threshold; should have merged (likely a config issue)
}

CLUSTER_PAIR_RECOMMENDATIONS = {
    "lower_threshold",          # same operation in spirit; relax τ to merge
    "accept_split",             # genuinely different operations; current split is correct
    "investigate_embedding",    # commands look similar but the embedding rates them dissimilar
    "investigate_scalars",      # the scalar block is over-separating same-behaviour clusters
}


class ClusterPairExplanation(BaseModel):
    """LLM-generated narrative explaining why two HDBSCAN session clusters
    were not merged into the same playbook. Inputs to the LLM are a curated
    subset of the structured analysis from `analyze_cluster_pair`."""
    verdict: str
    evidence: str
    recommendation: str
    rationale: str = ""

    @field_validator("verdict")
    @classmethod
    def _verdict_in_set(cls, v: str) -> str:
        v2 = (v or "").strip().lower()
        return v2 if v2 in CLUSTER_PAIR_VERDICTS else "marginal_split"

    @field_validator("recommendation")
    @classmethod
    def _recommendation_in_set(cls, v: str) -> str:
        v2 = (v or "").strip().lower()
        return v2 if v2 in CLUSTER_PAIR_RECOMMENDATIONS else "accept_split"


CLUSTER_PAIR_EXPLANATION_JSON_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "verdict": {
            "type": "string",
            "enum": sorted(CLUSTER_PAIR_VERDICTS),
            "description": (
                "One of: 'semantic_split' (different commands drive the gap), "
                "'behavioural_split' (similar commands; scalars differ), 'both', "
                "'marginal_split' (close to threshold; many small things), "
                "'near_duplicate' (sim ≥ threshold; should have merged)."
            ),
        },
        "evidence": {
            "type": "string",
            "description": (
                "2-3 sentences in plain English citing specific commands and "
                "numbers from the analysis."
            ),
            "minLength": 30,
            "maxLength": 800,
        },
        "recommendation": {
            "type": "string",
            "enum": sorted(CLUSTER_PAIR_RECOMMENDATIONS),
            "description": (
                "One of: 'lower_threshold', 'accept_split', "
                "'investigate_embedding', 'investigate_scalars'."
            ),
        },
        "rationale": {
            "type": "string",
            "description": "One sentence explaining the recommendation.",
            "maxLength": 400,
        },
    },
    "required": ["verdict", "evidence", "recommendation"],
    "additionalProperties": False,
}
